"""add source name for file model

Revision ID: 229e46a01a27
Revises: b48ad7df3ce0
Create Date: 2021-11-10 05:48:27.143388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229e46a01a27'
down_revision = 'b48ad7df3ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('source_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'source_name')
    # ### end Alembic commands ###
